/*
 * backend/services/pdfWorker.js
 * Worker thread for PDF generation to avoid blocking the main event loop
 */

const { parentPort, workerData } = require('worker_threads');
const PDFDocument = require('pdfkit');

function generatePDF(reportType, data) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const buffers = [];

      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfBuffer = Buffer.concat(buffers);
        resolve(pdfBuffer);
      });
      doc.on('error', reject);

      // PDF Content
      doc.fontSize(24).text('Monthly Analytics Report', { align: 'center' });
      doc.moveDown();
      doc.fontSize(12).text(
        `Generated: ${new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}`,
        { align: 'center' }
      );
      doc.moveDown(2);

      // Key Metrics Section
      doc.fontSize(16).text('Key Performance Indicators', { underline: true });
      doc.moveDown();

      const metrics = [
        ['Total Schools', data.totalSchools || 'N/A'],
        ['Active Schools', data.activeSchools || 'N/A'],
        ['New Schools This Month', data.newSchoolsThisMonth || 'N/A'],
        ['Total Students', data.totalStudents || 'N/A'],
        ['Events This Month', data.eventsThisMonth || 'N/A'],
        ['Revenue Collected', `KES ${data.revenueCollected ? data.revenueCollected.toLocaleString() : 'N/A'}`],
        ['Outstanding Payments', `KES ${data.outstandingPayments ? data.outstandingPayments.toLocaleString() : 'N/A'}`],
        ['Active Service Schools', data.activeServiceSchools || 'N/A'],
        ['Total Scouts Reached', data.totalScoutsReached || 'N/A'],
        ['Avg Attendance Rate', `${data.averageAttendanceRate || 0}%`],
        ['Schools Visited', data.schoolsVisited || 'N/A'],
        ['Trainer Rating', data.performanceRating ? `${data.performanceRating}/5.0` : 'N/A']
      ];

      metrics.forEach(([label, value]) => {
        doc.fontSize(11);
        doc.text(`${label}:`, { continued: true });
        doc.font('Helvetica-Bold').text(` ${value}`);
        doc.font('Helvetica');
      });

      doc.moveDown(2);

      // Notes
      doc.fontSize(10).fillColor('gray');
      doc.text('This is an automated report generated by the APV Management System.');
      doc.fillColor('black');

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

// Execute PDF generation and send result back to parent
generatePDF(reportType, workerData.data)
  .then((pdfBuffer) => {
    parentPort.postMessage({
      success: true,
      buffer: pdfBuffer.toString('base64'),
      bufferLength: pdfBuffer.length
    });
  })
  .catch((error) => {
    parentPort.postMessage({
      success: false,
      error: error.message
    });
  });
