/*
 * backend/services/reportScheduler.js
 * Cron job service for scheduled reports
 */

const cron = require('node-cron');
const ScheduledReport = require('../../models/ScheduledReport');
const emailService = require('./emailService');
const { getKPIMetrics } = require('../utils/aggregations');
const Event = require('../../models/Event');
const School = require('../../models/School');
const User = require('../../models/User');

class ReportScheduler {
  constructor() {
    this.cronJob = null;
  }

  /**
   * Start the scheduler
   */
  start() {
    // Run every minute to check for due reports
    this.cronJob = cron.schedule('* * * * *', async () => {
      await this.processScheduledReports();
    }, {
      scheduled: true,
      timezone: "Africa/Nairobi" // Kenya timezone
    });

    console.log('Report scheduler started (runs every minute)');
  }

  /**
   * Generate PDF document for scheduled report
   */
  async generatePDF(reportType, data) {
    return new Promise((resolve, reject) => {
      const PDFDocument = require('pdfkit');
      const doc = new PDFDocument({ margin: 50 });
      const buffers = [];
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfData = Buffer.concat(buffers);
        resolve(pdfData);
      });
      doc.on('error', reject);

      // PDF Content
      doc.fontSize(24).text('Monthly Analytics Report', { align: 'center' });
      doc.moveDown();
      doc.fontSize(12).text(`Generated: ${new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}`, { align: 'center' });
      doc.moveDown(2);

      // Key Metrics Section
      doc.fontSize(16).text('Key Performance Indicators', { underline: true });
      doc.moveDown();

      const metrics = [
        ['Total Schools', data.totalSchools || 'N/A'],
        ['Events This Month', data.eventsThisMonth || 'N/A'],
        ['Trainers Deployed', data.trainersDeployed || 'N/A'],
        ['Total Scouts Reached', data.totalScoutsReached || 'N/A'],
        ['Revenue Collected', `KES ${data.revenueCollected ? data.revenueCollected.toLocaleString() : 'N/A'}`],
        ['Outstanding Payments', `KES ${data.outstandingPayments ? data.outstandingPayments.toLocaleString() : 'N/A'}`],
        ['Report Submission Rate', `${data.reportSubmissionRate || 'N/A'}%`]
      ];

      metrics.forEach(([label, value]) => {
        doc.fontSize(11);
        doc.text(`${label}:`, { continued: true });
        doc.font('Helvetica-Bold').text(` ${value}`);
        doc.font('Helvetica');
      });

      doc.moveDown(2);

      // Notes
      doc.fontSize(10).fillColor('gray');
      doc.text('This is an automated report generated by the APV Management System.');
      doc.fillColor('black');

      doc.end();
    });
  }

  /**
   * Process all scheduled reports that are due
   */
  async processScheduledReports() {
    const now = new Date();

    try {
      // Find all active scheduled reports that are due
      const dueReports = await ScheduledReport.find({
        isActive: true,
        nextSendAt: { $lte: now },
        $or: [
          { expiresAt: { $exists: false } },
          { expiresAt: { $gte: now } }
        ]
      }).populate('createdBy', 'name email')
        .populate('recipients', 'name email');

      if (dueReports.length === 0) return;

      console.log(`Processing ${dueReports.length} scheduled report(s)`);

      for (const report of dueReports) {
        try {
          // Generate report data based on type
          const reportData = await this.generateReportData(report.reportType, report.config);

          // Create PDF attachment
          const pdfBuffer = await this.generatePDF(report.reportType, reportData);

          // Get recipient emails
          const recipients = report.recipients.map(r => ({
            name: r.name || '',
            email: r.email
          }));

          // Send email to each recipient
          for (const recipient of recipients) {
            await emailService.sendReportEmail(recipient, reportData, [
              {
                filename: `${report.reportType}_report_${new Date().toISOString().split('T')[0]}.pdf`,
                content: pdfBuffer,
                contentType: 'application/pdf'
              }
            ]);
          }

          // Update last sent and next send dates
          report.lastSentAt = now;
          report.nextSendAt = this.calculateNextSendDate(report.frequency);

          await report.save();

          console.log(`✓ Sent scheduled report: ${report.name} to ${recipients.length} recipient(s)`);
        } catch (error) {
          console.error(`Error processing scheduled report ${report._id}:`, error);
          // Log error but continue with other reports
        }
      }
    } catch (error) {
      console.error('Error in scheduled report processing:', error);
    }
  }

  /**
   * Generate report data based on type
   */
  async generateReportData(reportType, config) {
    // Use KPI metrics for monthly summary
    if (reportType === 'monthly_summary') {
      const kpis = await getKPIMetrics('30d');
      const totalSchools = await School.countDocuments();
      const monthlyEvents = await Event.countDocuments({
        startDate: {
          $gte: new Date(new Date().getFullYear(), new Date().getMonth(), 1)
        }
      });

      return {
        totalSchools,
        eventsThisMonth: monthlyEvents,
        ...kpis
      };
    }

    // For other types, use aggregations
    // This can be extended based on needed report types
    return { message: 'Report generation not implemented for this type' };
  }

  /**
   * Calculate next send date based on frequency
   */
  calculateNextSendDate(frequency) {
    const next = new Date();
    switch (frequency) {
      case 'daily':
        next.setDate(next.getDate() + 1);
        break;
      case 'weekly':
        next.setDate(next.getDate() + 7);
        break;
      case 'monthly':
        next.setDate(1);
        next.setMonth(next.getMonth() + 1);
        if (next.getMonth() === 0) next.setFullYear(next.getFullYear() + 1);
        break;
      case 'quarterly':
        next.setMonth(next.getMonth() + 3);
        break;
    }
    // Reset to midnight
    next.setHours(0, 0, 0, 0);
    return next;
  }
}

// Export singleton instance
module.exports = new ReportScheduler();
